### 1. GET /api/categories
GET /api/categories
Host: localhost:8082
Accept: application/json

### 2. GET /api/categories/{id}
GET /api/categories/e6a148d1-90a3-4fb3-8f6e-7885cd24e8ae
Host: localhost:8082
Accept: application/json

### 3. PUT /api/categories/{id}
PUT /api/categories/a6a148d1-90a3-4fb3-8f6e-7885cd24e8ae
Host: localhost:8082
Content-Type: application/json
Accept: application/json

{
  "name": "Clarinet",
  "description": "Clarinet"
}

### 4. DELETE /api/categories/{id}
DELETE /api/categories/e6a148d1-90a3-4fb3-8f6e-7885cd24e8ae
Host: localhost:8082
Accept: application/json